### ISSUE TITLE
model_detail

### ISSUE THREAD

**Issue by Hongzl1996** [smallhaolzh/tf-seq2tree#1]
Hi,

I am wandering if the model is the same as that described in _Language to Logical Form with Neural Attention_ ?

**Comment by ZhihaoLZH** [comment]
Hi,
I have reimplemented the experiment following the paper, and I ran the code to get the best result matching the proprosed one in the paper. However , I have no save the model and you can clone it and add some code to it. Finally, if you find some problems about the implementation , you can make an issue in the github.


All the best,
Liang.



At 2018-10-02 10:58:41, "Hong Zelin" <notifications@github.com> wrote:


Hi,

I am wandering if the model is the same as that described in Language to Logical Form with Neural Attention ?
